### ISSUE TITLE
BDD - déterminer la structure et les types nécessaires

### ISSUE THREAD

**Issue by sopero** [datalab-greta/Web-scraping-python-Groupe-Sondra-Marceline-Tarik#23]

**Comment by Marceline37** [comment]
Index AUTO INCREMENT CLE PRIMAIRE
Reference VARCAHR (15)
titre de l'offre TEXT (100)
localisation VARCHAR (100)
experience VARCHAR (50)
Date de publication VARCHAR (100)
Date 1  CURRENT_DATE (50)
Date Last  CURRENT_DATE (50)
Description LONGTEXT
Salaire VARCHAR (150)
Savoir faire TEXT
Savoir-être TEXT
Nom de l'entreprise CHAR (255)
Partenaire CHAR (100)

**Comment by sopero** [comment]
possible code
besoin de la confirmation des noms des colonnes en fonction des restrictions mysql
datefirst et datelast - examen du type de mysql défini  - date() ou now()

mySQLengine.execute("DROP TABLE IF EXISTS PEScraping ;")
mySQLengine.execute("SET FOREIGN_KEY_CHECKS = 1;");

mySQLengine.execute("""
CREATE TABLE IF NOT EXISTS `BDD_PE`.`PEScraping` (
 `id` int(10) NOT NULL AUTO_INCREMENT,
 `num_offre` varchar(7) COLLATE utf8_unicode_ci NOT NULL,
 `titre` varchar(80) COLLATE utf8_unicode_ci NULL,
 `date_publication` varchar(80) COLLATE utf8_unicode_ci NULL,
 `experience` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `city` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
 `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
 `contratdd` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
 `contratheures` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
 `salaire` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
 `savoirsfaire` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `savoiretre` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `qualifications` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `secteuractv` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
 `entreprise` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
 `partenaire` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
 `datefirst` date() NULL DEFAULT NULL,
 `datelast` date() NULL DEFAULT NULL,
 PRIMARY KEY (`id`)) 
ENGINE=InnoDB 
AUTO_INCREMENT=0 
DEFAULT CHARSET=utf8 
COLLATE=utf8_unicode_ci;  
""")

**Comment by sopero** [comment]
Finale

CREATE TABLE IF NOT EXISTS `Job_Bot_SMT`.`POLE_EMPLOI` (
  
  NumOffre VARCHAR(250) NOT NULL,
  title VARCHAR(261) NULL DEFAULT NULL,
  Localisation VARCHAR(250) NULL DEFAULT NULL,
  Experiences VARCHAR(250) NULL DEFAULT NULL,
  Date_publication VARCHAR(250) NULL DEFAULT NULL,
  Description VARCHAR(6000) NULL DEFAULT NULL,
  Contrat VARCHAR(250) NULL DEFAULT NULL,
  Horaires_Contrat VARCHAR(250) NULL DEFAULT NULL,
  Salaire VARCHAR(250) NULL DEFAULT NULL,
  Savoirsfaire VARCHAR(3000) NULL DEFAULT NULL,
  Savoir_etre VARCHAR(1000) NULL DEFAULT NULL,
  Formation VARCHAR(250) NULL DEFAULT NULL,
  Qualifications VARCHAR(250) NULL DEFAULT NULL,
  Secteur VARCHAR(250) NULL DEFAULT NULL,
  Entreprise VARCHAR(250) NULL DEFAULT NULL,
  Partenaire VARCHAR(250) NULL DEFAULT NULL,
  Datefirst VARCHAR(10) ,
  Datelast VARCHAR(10),
 PRIMARY KEY (`NumOffre`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;
""")
